"""
Django settings for botanical_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
def get_env(name, default=None, cast=None, required=False):
    val = os.getenv(name, default)
    if required and not val:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    if cast is not None and val is not None:
        if cast is bool:
            return str(val).lower() in ("1", "true", "yes")
        try:
            return cast(val)
        except Exception:
            raise ImproperlyConfigured(f"Environment variable {name} can't be cast to {cast}")
    return val

SECRET_KEY = get_env("DJANGO_SECRET_KEY", default=None)

DEBUG = get_env("DJANGO_DEBUG", default="False", cast=bool)

if not SECRET_KEY:
    if DEBUG:
        # development fallback (only for local/dev)
        SECRET_KEY = "dev-secret-key-please-change" 
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in environment for production")


# SECURITY WARNING: don't run with debug turned on in production!

# Security settings
SESSION_COOKIE_SECURE = get_env("DJANGO_SESSION_COOKIE_SECURE", default="False", cast=bool)
CSRF_COOKIE_SECURE = get_env("DJANGO_CSRF_COOKIE_SECURE", default="False", cast=bool)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = int(get_env("DJANGO_SECURE_HSTS_SECONDS", default="0"))  # 0 while testing
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default="False", cast=bool)
SECURE_HSTS_PRELOAD = get_env("DJANGO_SECURE_HSTS_PRELOAD", default="False", cast=bool)
SECURE_SSL_REDIRECT = get_env("DJANGO_SECURE_SSL_REDIRECT", default="False", cast=bool)
X_FRAME_OPTIONS = 'DENY'
ALLOWED_HOSTS = get_env("DJANGO_ALLOWED_HOSTS", 
                default="localhost,127.0.0.1").split(",")
SITE_URL = get_env("DJANGO_SITE_URL", default="http://127.0.0.1:8000")

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'plants'
]

JAZZMIN_SETTINGS = {
    # Site
    "site_title": "Botanical Garden",
    "site_header": "Garden Admin",
    "site_brand": "🌿 Botanical Garden",
    "site_logo": None,
    "welcome_sign": "Welcome to the Botanical Garden Admin Portal",
    "copyright": "Botanical Garden 2024",

    # Search
    "search_model": "plants.Plant",

    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],

    # User Menu
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,

    # Icons for models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "plants.Plant": "fas fa-leaf",
        "plants.PlantImage": "fas fa-images",
        "plants.QRCode": "fas fa-qrcode",
        "plants.ReportIssue": "fas fa-exclamation-triangle",
    },

    # Custom colors
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,

    # Theme
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-olive",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cerulean",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "menubar": "file edit view insert format tools table help",
    "plugins": """
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen insertdatetime media table
        paste code help wordcount emoticons hr pagebreak nonbreaking
        directionality visualchars autosave charmap codesample
    """,
    "toolbar": """
        undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |
        forecolor backcolor | alignleft aligncenter alignright alignjustify |
        bullist numlist outdent indent | link image media table |
        emoticons charmap hr pagebreak codesample | removeformat | fullscreen code
    """,
    "image_uploadtab": True,
    "automatic_uploads": True,
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'botanical_system.cache_headers.CacheControlForAuthMiddleware', # custom middleware
]

ROOT_URLCONF = 'botanical_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

 #For development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # for qr, img, pdf
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')

# local url(for development)

# production url(for pythonanywhere)

# Timezone settings
TIME_ZONE = 'Asia/Kolkata'  # Mumbai timezone
USE_TZ = True
# Format settings - This affects DISPLAY everywhere
USE_L10N = False  # Disable localization to use custom formats

# Custom datetime formats (applies everywhere)
DATETIME_FORMAT = 'd M Y, g:i a'  # 2 Oct 2025, 7:02 p.m.
DATE_FORMAT = 'd M Y'              # 2 Oct 2025
TIME_FORMAT = 'g:i a'              # 7:02 p.m.
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'  # 02/10/2025 19:02
